name: saucectl cypress tests with sys env

on:
  push:
    branches: [ main ]
  pull_request:

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Write secrets to the cypress.env.json file
        run: |
          echo '{"SWAG_USER": "${{secrets.SWAG_USER}}"}' > cypress.env.json  

      - name: Saucectl RUN example2
        uses: saucelabs/saucectl-run-action@v3
        with:
          config-file: .sauce/config-ex2.yml

      - name: Saucectl RUN example5
        uses: saucelabs/saucectl-run-action@v3
        with:
          config-file: .sauce/config-ex5.yml