name: saucectl cypress tests

on:
  push:
    branches: [ main ]
  pull_request:

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install sauceCtl
        run: |
          sudo sh -c 'curl -L https://saucelabs.github.io/saucectl/install | bash -s -- -b /usr/local/bin'
          saucectl --version

      - name: Saucectl RUN example2
        run: |
          saucectl run --config ./.sauce/config-ex2.yml

